CREATE DATABASE OKULKUTUPHANESI
USE OKULKUTUPHANESI;
CREATE TABLE UYELER(
	UYE_NO INT IDENTITY(1,1),
	UYE_ADI VARCHAR(20),
	UYE_SOYADI VARCHAR(20),
	CINSIYET VARCHAR(5),
	TELEFON VARCHAR(15),
	EPOSTA VARCHAR(40),
	ADRES_NO INT,
	PRIMARY KEY("UYE_NO")
);

ALTER TABLE UYELER ADD CONSTRAINT "FK_ADRESLER_UYELER"
FOREIGN KEY (ADRES_NO) REFERENCES ADRESLER(ADRES_NO);

CREATE TABLE ADRESLER(
	ADRES_NO INT IDENTITY(1,1),
	CADDE NVARCHAR (25),
	MAHALLE NVARCHAR (25),
	BINA_NO NVARCHAR (25),
	SEHIR  NVARCHAR (25),
	POSTA_KODU  INT,
	ULKE  NVARCHAR (25),
	PRIMARY KEY ("ADRES_NO")
);

CREATE TABLE EMANET(
	EMANET_NO INT IDENTITY(1,1),
	ISBN VARCHAR(20)NOT NULL,
	UYE_NO INT NOT NULL,
	KUTUPHANE_NO INT NOT NULL,
	EMANET_TARIHI DATETIME,
	TESLIM_TARIHI DATETIME,
	PRIMARY KEY("EMANET_NO")
);

ALTER TABLE EMANET ADD CONSTRAINT "FK_EMANET_UYELER"
FOREIGN KEY (UYE_NO) REFERENCES UYELER(UYE_NO);


CREATE TABLE KITAPLAR(
	ISBN VARCHAR(20),
	KITAP_ADI VARCHAR(20),
	YAYIN_TARIHI VARCHAR(20),
	S_SAYISI INT,
	PRIMARY KEY ("ISBN")
);


CREATE TABLE KATEGORILER(
	KATEGORI_NO INT IDENTITY(1,1),
	KATEGORI_ADI VARCHAR(20),
	PRIMARY KEY ("KATEGORI_NO")
);


CREATE TABLE YAZARLAR(
	YAZAR_NO INT IDENTITY(1,1),
	YAZAR_ADI VARCHAR(20),
	YAZAR_SOYADI VARCHAR(20),
	PRIMARY KEY ("YAZAR_NO")
);


CREATE TABLE KUTUPHANE(
	KUTUPHANE_NO INT IDENTITY(1,1),
	KUTUPHANE_ADI VARCHAR(20),
	ACIKLAMA VARCHAR(20),
	ADRES_NO INT,
	PRIMARY KEY ("KUTUPHANE_NO")
);
ALTER TABLE KUTUPHANE ADD CONSTRAINT "KUTUPHANE_ADRESLER"
FOREIGN KEY (ADRES_NO) REFERENCES ADRESLER(ADRES_NO);


CREATE TABLE KITAP_KUTUPHANE(
	KUTUPHANE_NO INT NOT NULL,
	ISBN VARCHAR(20) NOT NULL,
	MIKTAR INT,
	CONSTRAINT "KITAP_KUTUPHANE_PK" PRIMARY KEY ("KUTUPHANE_NO", "ISBN"),
	CONSTRAINT "KITAP_KUTUPHANE_FK" FOREIGN KEY ("KUTUPHANE_NO") REFERENCES KATEGORILER(KATEGORI_NO)
);ALTER TABLE KITAP_KUTUPHANE ADD CONSTRAINT "KITAP_KUTUPHANE_KITAPLAR_FK" FOREIGN KEY ("ISBN") REFERENCES KITAPLAR(ISBN);

CREATE TABLE KITAP_KATEGORI(
	ISBN VARCHAR(20) NOT NULL,
	KATEGORI_NO INT NOT NULL,
	CONSTRAINT "KITAP_KATEGORI_PK" PRIMARY KEY ("KATEGORI_NO", "ISBN"),
	CONSTRAINT "FK_ISBN" FOREIGN KEY ("ISBN") REFERENCES KITAPLAR("ISBN")
);

CREATE TABLE KITAP_YAZAR(
	ISBN VARCHAR(20) NOT NULL,
	YAZAR_NO INT NOT NULL,
	CONSTRAINT "KITAP_YAZAR_PK" PRIMARY KEY ("YAZAR_NO", "ISBN"),
	CONSTRAINT "FK_KITAP_YAZAR_ISBN" FOREIGN KEY ("ISBN") REFERENCES KITAPLAR("ISBN"),
	CONSTRAINT "FK_KITAP_YAZAR_YAZAR_NO" FOREIGN KEY ("YAZAR_NO") REFERENCES YAZARLAR("YAZAR_NO")
);